title: Frederik Holm Strøm
description: Rust developer based in Copenhagen, working as a Full Stack Developer at Factbird.
timezone: Etc/UTC

email: contact@frederikstroem.com

permalink: /journal/:title
date_format: "%Y-%m-%d"

# TODO: Eventually migrate to Jekyll-compiled Sass using @use rules with Bulma once github-pages have stable Dart Sass support via jekyll-sass-converter? See:
# - https://github.com/github/pages-gem/issues/813
# - https://github.com/jekyll/jekyll-sass-converter/issues/105
# - https://github.com/jekyll/jekyll-sass-converter/issues/116
# - https://stackoverflow.com/questions/61326061/does-jekyll-support-use-sass-statement
# - https://sass-lang.com/documentation/at-rules/use/
# - https://sass-lang.com/documentation/at-rules/import/
#sass:
#  style: compressed

defaults:
  - scope:
      path: assets/img
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - devenv.lock
  - devenv.nix
  - devenv.yaml
  - flake.lock
  - flake.nix
  - git_hooks
  - node_modules/
  - package-lock.json
  - package.json
  - renovate.json
  - scripts/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank
