title: Frederik Holm Strøm
description: My name is Frederik Holm Strøm, and I am currently studying Software Engineering at The University of Southern Denmark.
timezone: Etc/UTC

permalink: /journal/:title
date_format: "%Y-%m-%d"

sass:
  style: compressed

defaults:
  - scope:
      path: assets/img
    values:
      image: true

exclude:
  - README.md
  - run.sh
  - update.sh

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank
